### ISSUE TITLE
Pattern not found: joplin_token ="xxxxxxx.." on Win10 with GVIM 8.2

### ISSUE THREAD

**Issue by echaya** [tenfyzhong/joplin.vim#3]
Hi, 

I just installed the plug-in and setup the joplin_token in my .vimrc. When launching GVIM, I got the following error:

Pattern not found: joplin——token = "xxxxxx"
joplin.vim: please set g:joplin_token first.

Im using the jopline desktop win version (2.1.7) and confirmed the web clipper service is enabled and working on my chrome. Any suggestion?

thanks!

PS: understand there is a change of web clipper mechanism with jopline 2.1.x from 2.0.x (https://chrome.google.com/webstore/detail/joplin-web-clipper/alofnhikmmkdbbbgpnglcpdollgjjfek?hl=en-GB) => Does this change break the plug-in?

**Comment by tenfyzhong** [comment]
show me your setting

**Comment by echaya** [comment]
> show me your setting

i just realized that i didn't set the token properly. after setting the joplin_token, now i get the following error msg:


>Messages maintainer: Bram Moolenaar <Bram@vim.org>
>Error detected while processing D:\Dropbox\software\vim\vimfiles\plugged\joplin.vim\autoload\joplin.vim:
>line   10:
>Traceback (most recent call last):
  >File "<string>", line 2, in <module>
  >File "D:\Dropbox\software\vim\vimfiles\plugged\joplin.vim\python3\pyjoplin\__init__.py", line 4, in <module>
    >from .win import win
  >File "D:\Dropbox\software\vim\vimfiles\plugged\joplin.vim\python3\pyjoplin\win.py", line 12, in <module>
    >from . import joplin, options, tree, variable
  >File "D:\Dropbox\software\vim\vimfiles\plugged\joplin.vim\python3\pyjoplin\joplin.py", line 5, in <module>
    >import requests
>ModuleNotFoundError: No module named 'requests'
>Error detected while processing function joplin#toggle:
>line    1:
>Traceback (most recent call last):
  >File "<string>", line 1, in <module>
>NameError: name 'pyjoplin' is not defined

**Comment by echaya** [comment]
now I pip installed `requests`, i get:

>Messages maintainer: Bram Moolenaar <Bram@vim.org>
>Traceback (most recent call last):
>  File "<string>", line 1, in <module>
>  File "D:\Dropbox\software\vim\vimfiles\plugged\joplin.vim\python3\pyjoplin\win.py", line 469, in cmd_o
>    self.edit('edit', treenode)
>  File "D:\Dropbox\software\vim\vimfiles\plugged\joplin.vim\python3\pyjoplin\win.py", line 370, in edit
>    self._edit_note(command, True, treenode.node, treenode.lineno)
>  File "D:\Dropbox\software\vim\vimfiles\plugged\joplin.vim\python3\pyjoplin\win.py", line 338, in _edit_note
>    vim.current.buffer.vars['joplin_updated'] = note.updated_time
>OverflowError: Python int too large to convert to C long
>Traceback (most recent call last):
>  File "<string>", line 1, in <module>
>  File "D:\Dropbox\software\vim\vimfiles\plugged\joplin.vim\python3\pyjoplin\win.py", line 469, in cmd_o
>    self.edit('edit', treenode)
>  File "D:\Dropbox\software\vim\vimfiles\plugged\joplin.vim\python3\pyjoplin\win.py", line 370, in edit
>    self._edit_note(command, True, treenode.node, treenode.lineno)
>  File "D:\Dropbox\software\vim\vimfiles\plugged\joplin.vim\python3\pyjoplin\win.py", line 338, in _edit_note
>    vim.current.buffer.vars['joplin_updated'] = note.updated_time
>OverflowError: Python int too large to convert to C long

I can see this plug-in of great potential. Maybe you could update the readme.md to better illustrate the dependency / env required to have it running on other's PC / terminal. until then :)
